/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 11.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HBARRIER
#define HCPP_HBARRIER

namespace HalconCpp
{

// Represents an instance of a barrier synchronization object.
class LIntExport HBarrier : public HToolBase
{

public:

  // Create an uninitialized instance
  HBarrier():HToolBase() {}

  // Copy constructor
  HBarrier(const HBarrier& source) : HToolBase(source) {}

  // Create HBarrier from handle, taking ownership
  explicit HBarrier(Hlong handle);

  // Set new handle, taking ownership
  void SetHandle(Hlong handle);



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // create_barrier: Create a barrier synchronization object.
  explicit HBarrier(const HTuple& AttribName, const HTuple& AttribValue, Hlong TeamSize);

  // create_barrier: Create a barrier synchronization object.
  explicit HBarrier(const HString& AttribName, const HString& AttribValue, Hlong TeamSize);

  // create_barrier: Create a barrier synchronization object.
  explicit HBarrier(const char* AttribName, const char* AttribValue, Hlong TeamSize);




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Wait on the release of a barrier synchronization object.
  void WaitBarrier() const;

  // Create a barrier synchronization object.
  void CreateBarrier(const HTuple& AttribName, const HTuple& AttribValue, Hlong TeamSize);

  // Create a barrier synchronization object.
  void CreateBarrier(const HString& AttribName, const HString& AttribValue, Hlong TeamSize);

  // Create a barrier synchronization object.
  void CreateBarrier(const char* AttribName, const char* AttribValue, Hlong TeamSize);

};

class LIntExport HBarrierArray : public HToolArray
{
public:
  HBarrierArray();
  HBarrierArray(HBarrier* classes, Hlong length);
protected:
  virtual void CreateArray(Hlong length);
};

}

#endif
