/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 11.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HCOMPUTEDEVICE
#define HCPP_HCOMPUTEDEVICE

namespace HalconCpp
{

// Class representing a compute device handle.
class LIntExport HComputeDevice : public HToolBase
{

public:

  // Create an uninitialized instance
  HComputeDevice():HToolBase() {}

  // Copy constructor
  HComputeDevice(const HComputeDevice& source) : HToolBase(source) {}

  // Set new handle, taking ownership
  void SetHandle(Hlong handle);



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // open_compute_device: Open a compute device.
  explicit HComputeDevice(Hlong DeviceIdentifier);




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Query compute device parameters.
  HTuple GetComputeDeviceParam(const HString& ParamName) const;

  // Query compute device parameters.
  HTuple GetComputeDeviceParam(const char* ParamName) const;

  // Set parameters of an compute device.
  void SetComputeDeviceParam(const HString& ParamName, const HTuple& ParamValue) const;

  // Set parameters of an compute device.
  void SetComputeDeviceParam(const HString& ParamName, const HString& ParamValue) const;

  // Set parameters of an compute device.
  void SetComputeDeviceParam(const char* ParamName, const char* ParamValue) const;

  // Close all compute devices.
  static void ReleaseAllComputeDevices();

  // Close a compute_device.
  void ReleaseComputeDevice() const;

  // Deactivate all compute devices.
  static void DeactivateAllComputeDevices();

  // Activate a compute device.
  void ActivateComputeDevice() const;

  // Initialize a compute device.
  void InitComputeDevice(const HTuple& Operators) const;

  // Open a compute device.
  void OpenComputeDevice(Hlong DeviceIdentifier);

  // Get information on a compute device.
  static HTuple GetComputeDeviceInfo(Hlong DeviceIdentifier, const HString& InfoName);

  // Get information on a compute device.
  static HTuple GetComputeDeviceInfo(Hlong DeviceIdentifier, const char* InfoName);

  // Get the list of available compute devices.
  static HTuple QueryAvailableComputeDevices();

};

class LIntExport HComputeDeviceArray : public HToolArray
{
public:
  HComputeDeviceArray();
  HComputeDeviceArray(HComputeDevice* classes, Hlong length);
protected:
  virtual void CreateArray(Hlong length);
};

}

#endif
