/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 11.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HCONDITION
#define HCPP_HCONDITION

namespace HalconCpp
{

// Represents an instance of a condition synchronization object.
class LIntExport HCondition : public HToolBase
{

public:

  // Create an uninitialized instance
  HCondition():HToolBase() {}

  // Copy constructor
  HCondition(const HCondition& source) : HToolBase(source) {}

  // Create HCondition from handle, taking ownership
  explicit HCondition(Hlong handle);

  // Set new handle, taking ownership
  void SetHandle(Hlong handle);



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // create_condition: Create a condition variable synchronization object.
  explicit HCondition(const HTuple& AttribName, const HTuple& AttribValue);

  // create_condition: Create a condition variable synchronization object.
  explicit HCondition(const HString& AttribName, const HString& AttribValue);

  // create_condition: Create a condition variable synchronization object.
  explicit HCondition(const char* AttribName, const char* AttribValue);




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Signal a condition synchronization object.
  void BroadcastCondition() const;

  // Signal a condition synchronization object.
  void SignalCondition() const;

  // Bounded wait on the signal of a condition synchronization object.
  void TimedWaitCondition(const HMutex& MutexHandle, Hlong Timeout) const;

  // wait on the signal of a condition synchronization object.
  void WaitCondition(const HMutex& MutexHandle) const;

  // Create a condition variable synchronization object.
  void CreateCondition(const HTuple& AttribName, const HTuple& AttribValue);

  // Create a condition variable synchronization object.
  void CreateCondition(const HString& AttribName, const HString& AttribValue);

  // Create a condition variable synchronization object.
  void CreateCondition(const char* AttribName, const char* AttribValue);

};

class LIntExport HConditionArray : public HToolArray
{
public:
  HConditionArray();
  HConditionArray(HCondition* classes, Hlong length);
protected:
  virtual void CreateArray(Hlong length);
};

}

#endif
