/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 11.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HLEXICON
#define HCPP_HLEXICON

namespace HalconCpp
{

// Represents an instance of a lexicon.
class LIntExport HLexicon : public HToolBase
{

public:

  // Create an uninitialized instance
  HLexicon():HToolBase() {}

  // Copy constructor
  HLexicon(const HLexicon& source) : HToolBase(source) {}

  // Create HLexicon from handle, taking ownership
  explicit HLexicon(Hlong handle);

  // Set new handle, taking ownership
  void SetHandle(Hlong handle);



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // import_lexicon: Create a lexicon from a text file.
  explicit HLexicon(const HString& Name, const HString& FileName);

  // import_lexicon: Create a lexicon from a text file.
  explicit HLexicon(const char* Name, const char* FileName);

  // create_lexicon: Create a lexicon from a tuple of words.
  explicit HLexicon(const HString& Name, const HTuple& Words);

  // create_lexicon: Create a lexicon from a tuple of words.
  explicit HLexicon(const char* Name, const HTuple& Words);




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Find a similar word in a lexicon.
  HString SuggestLexicon(const HString& Word, Hlong* NumCorrections) const;

  // Find a similar word in a lexicon.
  HString SuggestLexicon(const char* Word, Hlong* NumCorrections) const;

  // Check if a word is contained in a lexicon.
  Hlong LookupLexicon(const HString& Word) const;

  // Check if a word is contained in a lexicon.
  Hlong LookupLexicon(const char* Word) const;

  // Query all words from a lexicon.
  HTuple InspectLexicon() const;

  // Create a lexicon from a text file.
  void ImportLexicon(const HString& Name, const HString& FileName);

  // Create a lexicon from a text file.
  void ImportLexicon(const char* Name, const char* FileName);

  // Create a lexicon from a tuple of words.
  void CreateLexicon(const HString& Name, const HTuple& Words);

  // Create a lexicon from a tuple of words.
  void CreateLexicon(const char* Name, const HTuple& Words);

};

class LIntExport HLexiconArray : public HToolArray
{
public:
  HLexiconArray();
  HLexiconArray(HLexicon* classes, Hlong length);
protected:
  virtual void CreateArray(Hlong length);
};

}

#endif
