/***********************************************************
 * File generated by the HALCON-Compiler hcomp version 11.0
 * Usage: Interface to C++
 *
 * Software by: MVTec Software GmbH, www.mvtec.com
 ***********************************************************/


#ifndef HCPP_HMUTEX
#define HCPP_HMUTEX

namespace HalconCpp
{

// Represents an instance of a mutex synchronization object.
class LIntExport HMutex : public HToolBase
{

public:

  // Create an uninitialized instance
  HMutex():HToolBase() {}

  // Copy constructor
  HMutex(const HMutex& source) : HToolBase(source) {}

  // Create HMutex from handle, taking ownership
  explicit HMutex(Hlong handle);

  // Set new handle, taking ownership
  void SetHandle(Hlong handle);



/*****************************************************************************
 * Operator-based class constructors
 *****************************************************************************/

  // create_mutex: Create a mutual exclusion synchronization object.
  explicit HMutex(const HTuple& AttribName, const HTuple& AttribValue);

  // create_mutex: Create a mutual exclusion synchronization object.
  explicit HMutex(const HString& AttribName, const HString& AttribValue);

  // create_mutex: Create a mutual exclusion synchronization object.
  explicit HMutex(const char* AttribName, const char* AttribValue);




  /***************************************************************************
   * Operators                                                               *
   ***************************************************************************/

  // Unlock a mutex synchronization object.
  void UnlockMutex() const;

  // Lock a mutex synchronization object.
  Hlong TryLockMutex() const;

  // Lock a mutex synchronization object.
  void LockMutex() const;

  // Create a mutual exclusion synchronization object.
  void CreateMutex(const HTuple& AttribName, const HTuple& AttribValue);

  // Create a mutual exclusion synchronization object.
  void CreateMutex(const HString& AttribName, const HString& AttribValue);

  // Create a mutual exclusion synchronization object.
  void CreateMutex(const char* AttribName, const char* AttribValue);

};

class LIntExport HMutexArray : public HToolArray
{
public:
  HMutexArray();
  HMutexArray(HMutex* classes, Hlong length);
protected:
  virtual void CreateArray(Hlong length);
};

}

#endif
